# listaklientow_ui.rb --
#
# UI generated by GUI Builder Build 146 on 2009-05-18 17:50:06 from:
#    /home/che/Desktop/Video/listaklientow.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Use UTF-8 encoding
$KCODE = 'U'

require 'tk'
require 'klientdialog_ui'

class Listaklientow_ui
  def initialize(root)
    @root = root

    da = DataAccess.getInstance()

    # Widget Initialization
    @_listbox_1 = TkListbox.new(@root,
      'height' => 0,
      'width' => 0 ) 
    
    @clients = da.getClients()
     
    @clients.keys.each { |s| @_listbox_1.insert('end', s) }

    # @scrollBar = TkScrollbar.new(@root).pack('side'=>'right', 'fill'=>'y')
    
    # @scrollBar.command(proc { |args|
    #                     @_listbox_1.yview(*args)
    #                  })

    # @_listbox_1.yscrollcommand(proc { |first, last|
    #                      @scrollBar.set(first, last)
    #                    })


    @_label_1 = TkLabel.new(@root,
      'text' => "Klienci"
    )
    @_button_1 = TkButton.new(@root,
      'text' => "Dodaj"
    )
    @_button_2 = TkButton.new(@root,
      'text' => "Modyfikuj"
    )
    @_button_3 = TkButton.new(@root,
      'text' => "Usun"
    )
    @_entry_1 = TkEntry.new(@root,
      'width' => 0
    )
    @_button_4 = TkButton.new(@root,
      'text' => "Szukaj"
    )

    # widget commands

    @_listbox_1.configure(
      'xscrollcommand' => lambda {  }
    )
    @_listbox_1.configure(
      'yscrollcommand' => lambda { }
    )
    @_button_1.configure(
      'command' => lambda {
                         
                           t = TkToplevel.new(@root)
                           t.title('Dodaj klienta')

                           Klientdialog_ui.new(t, nil, "add", self)

                           #self.refresh()
                         
                         }
    )
    @_button_2.configure(
      'command' => lambda {
                           idx = @_listbox_1.curselection
                           if idx.length == 1
                             idx = idx[0]
                             
                             str = @_listbox_1.value()[idx]
                             client = @clients[str]
                             
                             t = TkToplevel.new(@root)
                             t.title('Modyfikuj dane klienta')

                             Klientdialog_ui.new(t, client, "modify", self)
                             
                             #self.refresh()

                           end

                         }
    )
    @_button_3.configure(
      'command' => lambda {
                           idx = @_listbox_1.curselection
                           if idx.length == 1
                             idx = idx[0]

                             str = @_listbox_1.value()[idx]
                             client = @clients[str]
                             
                             t = TkToplevel.new(@root)
                             t.title('Usuwanie klienta')
                             
                             Klientdialog_ui.new(t, client, "delete", self)
                             
                             #self.refresh()                            

                           end
                           
                         }
    )
    @_entry_1.configure(
      'invalidcommand' => lambda {  }
    )
    @_entry_1.configure(
      'validatecommand' => lambda {
                          
                          
                        }                
    )
    @_entry_1.configure(
      'xscrollcommand' => lambda { }
    )
    @_button_4.configure(
      'command' => lambda { 
                           @_listbox_1.clear
                           @clients.values.each { |v|
                             
                             reg = Regexp.new(".*"+@_entry_1.value+".*")
                             
                             if v.Imie =~ reg or v.Nazwisko =~ reg
                               
                               @_listbox_1.insert('end', @clients.index(v))
                               
                             end
                             
                           }
                         }
    )

    # Geometry Management
    @_listbox_1.grid(
      'in'     => @root,
      'column' => 3,
      'row'    => 3,
      'columnspan' => 2,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 4,
      'sticky' => "news"
    )
    @_label_1.grid(
      'in'     => @root,
      'column' => 3,
      'row'    => 1,
      'columnspan' => 2,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => ""
    )
    @_button_1.grid(
      'in'     => @root,
      'column' => 2,
      'row'    => 3,
      'columnspan' => 1,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => "ew"
    )
    @_button_2.grid(
      'in'     => @root,
      'column' => 2,
      'row'    => 4,
      'columnspan' => 1,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => "ew"
    )
    @_button_3.grid(
      'in'     => @root,
      'column' => 2,
      'row'    => 5,
      'columnspan' => 1,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => "ew"
    )
    @_entry_1.grid(
      'in'     => @root,
      'column' => 4,
      'row'    => 2,
      'columnspan' => 1,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => "ew"
    )
    @_button_4.grid(
      'in'     => @root,
      'column' => 5,
      'row'    => 2,
      'columnspan' => 1,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => ""
    )


    # Resize Behavior
    TkGrid.rowconfigure(@root, 1, 'weight' => 0, 'minsize' => 40, 'pad' => 0)
    TkGrid.rowconfigure(@root, 2, 'weight' => 0, 'minsize' => 40, 'pad' => 0)
    TkGrid.rowconfigure(@root, 3, 'weight' => 0, 'minsize' => 35, 'pad' => 0)
    TkGrid.rowconfigure(@root, 4, 'weight' => 0, 'minsize' => 36, 'pad' => 0)
    TkGrid.rowconfigure(@root, 5, 'weight' => 0, 'minsize' => 40, 'pad' => 0)
    TkGrid.rowconfigure(@root, 6, 'weight' => 0, 'minsize' => 85, 'pad' => 0)
    TkGrid.rowconfigure(@root, 7, 'weight' => 0, 'minsize' => 52, 'pad' => 0)
    TkGrid.columnconfigure(@root, 1, 'weight' => 0, 'minsize' => 36, 'pad' => 0)
    TkGrid.columnconfigure(@root, 2, 'weight' => 0, 'minsize' => 92, 'pad' => 0)
    TkGrid.columnconfigure(@root, 3, 'weight' => 0, 'minsize' => 281, 'pad' => 0)
    TkGrid.columnconfigure(@root, 4, 'weight' => 0, 'minsize' => 229, 'pad' => 0)
    TkGrid.columnconfigure(@root, 5, 'weight' => 0, 'minsize' => 92, 'pad' => 0)
  end
  
  def refresh()

    @clients = DataAccess.getInstance().getClients()
    @_listbox_1.clear

    @clients.keys.each { |k| @_listbox_1.insert('end', k) }
    
  end
end

