#!/usr/bin/env ruby
# listaklientow.rb --
#
# UI generated by GUI Builder Build 146 on 2009-05-18 17:50:07 from:
#    /home/che/Desktop/Video/listaklientow.ui
# This file is auto-generated.  Only the code within
#    '# BEGIN USER CODE (global|class)'
#    '# END USER CODE (global|class)'
# and code inside the callback defs will be round-tripped.
#

# Add script's directory to lib load path
$:.unshift File.dirname(__FILE__)
require 'listaklientow_ui'
require 'tk'

# BEGIN USER CODE global

# END USER CODE global

class Listaklientow < Listaklientow_ui

  # BEGIN CALLBACK CODE
  # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

  # _button_1_command --
  #
  # Callback to handle _button_1 widget option -command
  def _button_1_command(*args)

  end

  # _button_2_command --
  #
  # Callback to handle _button_2 widget option -command
  def _button_2_command(*args)

  end

  # _button_3_command --
  #
  # Callback to handle _button_3 widget option -command
  def _button_3_command(*args)

  end

  # _button_4_command --
  #
  # Callback to handle _button_4 widget option -command
  def _button_4_command(*args)

  end

  # _entry_1_invalidcommand --
  #
  # Callback to handle _entry_1 widget option -invalidcommand
  def _entry_1_invalidcommand(*args)

  end

  # _entry_1_validatecommand --
  #
  # Callback to handle _entry_1 widget option -validatecommand
  def _entry_1_validatecommand(*args)

  end

  # _entry_1_xscrollcommand --
  #
  # Callback to handle _entry_1 widget option -xscrollcommand
  def _entry_1_xscrollcommand(*args)

  end

  # _listbox_1_xscrollcommand --
  #
  # Callback to handle _listbox_1 widget option -xscrollcommand
  def _listbox_1_xscrollcommand(*args)

  end

  # _listbox_1_yscrollcommand --
  #
  # Callback to handle _listbox_1 widget option -yscrollcommand
  def _listbox_1_yscrollcommand(*args)

  end

  # END CALLBACK CODE

  # BEGIN USER CODE class

  # END USER CODE class
end

# Standalone Code Initialization - DO NOT EDIT
#
if $0 == __FILE__
  begin
    userinit
  rescue NameError
    # Ignore userinit not being defined
  end
  root = Tk.root
  root.title('listaklientow')
  dlg = Listaklientow.new(root)

  #root.protocol('WM_DELETE_WINDOW', lambda { exit })
  begin
    run
  rescue NameError
    # Ignore run not being defined
  end
  Tk.mainloop
end
