#!/usr/bin/env ruby
# loginDialog.rb --
#
# UI generated by GUI Builder Build 146 on 2009-05-17 16:23:41 from:
#    /home/che/Programy/Rails/loginDialog.ui
# This file is auto-generated.  Only the code within
#    '# BEGIN USER CODE (global|class)'
#    '# END USER CODE (global|class)'
# and code inside the callback defs will be round-tripped.
#

# Add script's directory to lib load path
$:.unshift File.dirname(__FILE__)
require 'loginDialog_ui'
require 'tk'

# BEGIN USER CODE global

# END USER CODE global

class LoginDialog < LoginDialog_ui

  # BEGIN CALLBACK CODE
  # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

  # _button_1_command --
  #
  # Callback to handle _button_1 widget option -command
  def _button_1_command(*args)

  end

  # _button_2_command --
  #
  # Callback to handle _button_2 widget option -command
  def _button_2_command(*args)

  end

  # _entry_1_invalidcommand --
  #
  # Callback to handle _entry_1 widget option -invalidcommand
  def _entry_1_invalidcommand(*args)

  end

  # _entry_1_validatecommand --
  #
  # Callback to handle _entry_1 widget option -validatecommand
  def _entry_1_validatecommand(*args)

  end

  # _entry_1_xscrollcommand --
  #
  # Callback to handle _entry_1 widget option -xscrollcommand
  def _entry_1_xscrollcommand(*args)

  end

  # _entry_2_invalidcommand --
  #
  # Callback to handle _entry_2 widget option -invalidcommand
  def _entry_2_invalidcommand(*args)

  end

  # _entry_2_validatecommand --
  #
  # Callback to handle _entry_2 widget option -validatecommand
  def _entry_2_validatecommand(*args)

  end

  # _entry_2_xscrollcommand --
  #
  # Callback to handle _entry_2 widget option -xscrollcommand
  def _entry_2_xscrollcommand(*args)

  end

  # END CALLBACK CODE

  # BEGIN USER CODE class

  # END USER CODE class
end

# Standalone Code Initialization - DO NOT EDIT
#
if $0 == __FILE__
  begin
    userinit
  rescue NameError
    # Ignore userinit not being defined
  end
  root = Tk.root
  root.title('loginDialog')
  dlg = LoginDialog.new(root)

  #root.protocol('WM_DELETE_WINDOW', lambda { exit })
  begin
    run
  rescue NameError
    # Ignore run not being defined
  end
  Tk.mainloop
end
