# loginDialog_ui.rb --
#
# UI generated by GUI Builder Build 146 on 2009-05-17 16:23:40 from:
#    /home/che/Programy/Rails/loginDialog.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Use UTF-8 encoding
$KCODE = 'U'

require 'tk'
require 'EkspedientPanel_ui'
require 'DataAccess'

class LoginDialog_ui 
  def initialize(root, parent)
    
    @parent = parent
    @root = root
    @root.title('Logowanie do systemu')
    
    
    # Widget Initialization
    @_label_1 = TkLabel.new(@root,
      'text' => "hasło:"
    )
    @_label_2 = TkLabel.new(@root,
      'text' => "login"
    )
    @_entry_2 = TkEntry.new(@root,
      'width' => 0
    )
    @_label_4 = TkLabel.new(@root,
      'text' => "Logowanie do systemu"
    )
    @_entry_1 = TkEntry.new(@root,
      'show' => "*",
      'width' => 0
    )
    @_button_1 = TkButton.new(@root,
      'text' => "OK"
    )
    @_button_2 = TkButton.new(@root,
      'text' => "Anuluj"
    )

    # widget commands

    @_entry_2.configure(
      'invalidcommand' => lambda { }
    )
    @_entry_2.configure(
      'validatecommand' => lambda { }
    )
    @_entry_2.configure(
      'xscrollcommand' => lambda { }
    )
    @_entry_1.configure(
      'invalidcommand' => lambda {  }
    )
    @_entry_1.configure(
      'validatecommand' => lambda {  }
    )
    @_entry_1.configure(
      'xscrollcommand' => lambda { }
    )
    @_button_1.configure(
      'command' => lambda { 

	@login = @_entry_2.get()
	@password = @_entry_1.get()
	
	puts "Login to: #{@login}, a haslo to #{@password}"
	
                         
        da = DataAccess.getInstance()
	
	if da.logIn(@login, @password)
	    puts "User exists in DB"
            @root.destroy()

            EkspedientPanel_ui.new(@parent, @login)
	else
	    puts "User unknown!"
            Tk::messageBox :message => 'User unknown!'
            
	end
   
    }
    )
    @_button_2.configure(
      'command' => lambda {
      
	exit

    }
    )


    # Geometry Management
    @_label_1.grid(
      'in'     => @root,
      'column' => 2,
      'row'    => 3,
      'columnspan' => 1,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => ""
    )
    @_label_2.grid(
      'in'     => @root,
      'column' => 2,
      'row'    => 2,
      'columnspan' => 1,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => ""
    )
    @_entry_2.grid(
      'in'     => @root,
      'column' => 3,
      'row'    => 2,
      'columnspan' => 2,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => "ew"
    )
    @_label_4.grid(
      'in'     => @root,
      'column' => 3,
      'row'    => 1,
      'columnspan' => 2,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => ""
    )
    @_entry_1.grid(
      'in'     => @root,
      'column' => 3,
      'row'    => 3,
      'columnspan' => 2,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => "ew"
    )
    @_button_1.grid(
      'in'     => @root,
      'column' => 3,
      'row'    => 4,
      'columnspan' => 1,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => "ne"
    )
    @_button_2.grid(
      'in'     => @root,
      'column' => 4,
      'row'    => 4,
      'columnspan' => 1,
      'ipadx' => 0,
      'ipady' => 0,
      'padx' => 0,
      'pady' => 0,
      'rowspan' => 1,
      'sticky' => "nw"
    )


    # Resize Behavior
    TkGrid.rowconfigure(@root, 1, 'weight' => 0, 'minsize' => 38, 'pad' => 0)
    TkGrid.rowconfigure(@root, 2, 'weight' => 0, 'minsize' => 40, 'pad' => 0)
    TkGrid.rowconfigure(@root, 3, 'weight' => 0, 'minsize' => 51, 'pad' => 0)
    TkGrid.rowconfigure(@root, 4, 'weight' => 0, 'minsize' => 34, 'pad' => 0)
    TkGrid.rowconfigure(@root, 5, 'weight' => 0, 'minsize' => 26, 'pad' => 0)
    TkGrid.columnconfigure(@root, 1, 'weight' => 0, 'minsize' => 23, 'pad' => 0)
    TkGrid.columnconfigure(@root, 2, 'weight' => 0, 'minsize' => 40, 'pad' => 0)
    TkGrid.columnconfigure(@root, 3, 'weight' => 0, 'minsize' => 136, 'pad' => 0)
    TkGrid.columnconfigure(@root, 4, 'weight' => 0, 'minsize' => 121, 'pad' => 0)
    TkGrid.columnconfigure(@root, 5, 'weight' => 0, 'minsize' => 65, 'pad' => 0)

  end
  
end

